// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BlockType = { "type": "Text" } | { "type": "Heading1" } | { "type": "Heading2" } | { "type": "Heading3" } | { "type": "BulletList" } | { "type": "NumberedList" } | { "type": "Todo", "data": { checked: boolean, } } | { "type": "Code", "data": { language: string, } } | { "type": "Quote" } | { "type": "Divider" } | { "type": "SubPage", "data": { page_id: string, } } | { "type": "PageLink", "data": { page_id: string, } };
