// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Page = { id: string, title: string, icon: string | null, cover: string | null, parent_id: string | null, is_archived: boolean, created_at: string, updated_at: string, };
