// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SearchFileGroup } from "./SearchFileGroup";

export type SearchResponse = { groups: Array<SearchFileGroup>, total_matches: number, };
