// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SearchMatch = { block_id: string, content: string, block_type: string, match_start: number, match_end: number, snippet: string, order: number, };
