// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SearchMatch } from "./SearchMatch";

export type SearchFileGroup = { page_id: string, page_title: string, page_icon: string | null, matches: Array<SearchMatch>, };
