// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlockType } from "./BlockType";

export type Block = { id: string, page_id: string, block_type: BlockType, content: string, parent_id: string | null, order: number, created_at: string, updated_at: string, };
